"""added mathes.score

Revision ID: c9f8f426ca0c
Revises: 4b3cab3f8ec7
Create Date: 2024-09-24 11:34:18.817589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f8f426ca0c'
down_revision: Union[str, None] = '4b3cab3f8ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_player_id', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_groups_group_name', table_name='groups')
    op.drop_table('groups')
    op.drop_table('playoffs')
    op.drop_index('ix_leagues_league_id', table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('matches')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_tournaments_tournament_id', table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    op.create_index('ix_tournaments_tournament_id', 'tournaments', ['tournament_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('player1_id', sa.INTEGER(), nullable=True),
    sa.Column('player2_id', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('group_name', sa.VARCHAR(), nullable=True),
    sa.Column('playoff_id', sa.INTEGER(), nullable=True),
    sa.Column('league_id', sa.INTEGER(), nullable=True),
    sa.Column('winner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player1_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['player2_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['playoff_id'], ['playoffs.playoff_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('leagues',
    sa.Column('league_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('n_groups', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.Column('players', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('league_id')
    )
    op.create_index('ix_leagues_league_id', 'leagues', ['league_id'], unique=False)
    op.create_table('playoffs',
    sa.Column('playoff_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('start_stage', sa.VARCHAR(), nullable=True),
    sa.Column('current_stage', sa.VARCHAR(), nullable=True),
    sa.Column('league_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playoff_id')
    )
    op.create_table('groups',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('group_name', sa.VARCHAR(), nullable=True),
    sa.Column('league_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.league_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_groups_group_name', 'groups', ['group_name'], unique=False)
    op.create_table('players',
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('patronymic', sa.VARCHAR(length=30), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index('ix_players_player_id', 'players', ['player_id'], unique=False)
    # ### end Alembic commands ###
