"""new migration

Revision ID: cc555a703d4c
Revises: fe24c913955c
Create Date: 2024-08-20 11:06:08.738721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc555a703d4c'
down_revision: Union[str, None] = 'fe24c913955c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_id', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_tournaments_id', table_name='tournaments')
    op.drop_index('ix_tournaments_name', table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index('ix_departments_id', table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_leagues_id', table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('n_groups', sa.INTEGER(), nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), nullable=True),
    sa.Column('players', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leagues_id', 'leagues', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_departments_id', 'departments', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tournaments_name', 'tournaments', ['name'], unique=False)
    op.create_index('ix_tournaments_id', 'tournaments', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('patronymic', sa.VARCHAR(length=30), nullable=True),
    sa.Column('sex', sa.VARCHAR(), nullable=False),
    sa.Column('department_id', sa.INTEGER(), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_players_id', 'players', ['id'], unique=False)
    # ### end Alembic commands ###
